name: format code

on:
  push:
    branches:
      - "**"

jobs:
  lintAndFormat:
    name: performs formatting
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: install pnpm
        run: npm install -g pnpm
        working-directory: ./frontend

      - name: format backend
        run: npm run format-check
        working-directory: ./backend

      - name: install dependencies on frontend
        run: pnpm install
        working-directory: ./frontend

      - name: format frontend
        run: pnpm run format-check
        working-directory: ./frontend
